name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - run: |
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
      - uses: pre-commit/action@v2.0.3
